baseURL = "http://bigspringfork.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Baker Writing"
[markup.goldmark.renderer]
unsafe = true
