import type { Citation } from "./types";
import { ANCHOR_LIBRARY } from "./anchors";

/* ---------- Prompts ----------
   These are server-side only (imported by the Netlify functions), but live in
   shared/ so the anchor library stays a single source of truth. */

export function buildConsensusPrompt(request: string): string {
  return `You are the evidence-retrieval stage of a grant research pipeline for an NCA-accredited Children's Advocacy Center.

Funding request under development:
"${request}"

Use the Consensus search tool to find peer-reviewed evidence supporting this request. Run focused searches on:
1. Children's Advocacy Center model effectiveness / multidisciplinary team response to child abuse
2. Trauma screening for maltreated children (validity, outcomes)
3. Family advocacy / caregiver support and engagement in child abuse cases
4. Identification and response to child sex trafficking / commercial sexual exploitation
5. Outcomes of coordinated investigation (reduced interviews, prosecution, service linkage)

After searching, list every relevant peer-reviewed paper you found. For each: authors, year, title, journal, DOI or URL if available, and a one-sentence finding relevant to this request. Only list papers actually returned by the search tool — do not add papers from memory.`;
}

export function buildStructuringPrompt(rawSearchOutput: string): string {
  return `Below is raw output from a peer-reviewed literature search. Extract ONLY papers explicitly present in this text. Respond with ONLY a JSON object: {"citations":[{"id":"C1","authors":"...","year":"...","title":"...","source":"journal + DOI/URL if present","finding":"one-sentence relevant finding"}]}. Number sequentially C1, C2, ... Maximum 8 citations, and keep every field under 25 words so the full JSON stays short. If no clearly identifiable papers, return {"citations":[]}.

=== RAW SEARCH OUTPUT ===
${rawSearchOutput.slice(0, 9000)}`;
}

/* Per-section specs. Each section is generated by its OWN small API call
   returning PLAIN MARKDOWN — no JSON in the synthesis path, so a token-limit
   truncation can never corrupt a parse. */
export const SECTION_SPECS: Record<string, string> = {
  needStatement:
    "A compelling 2–3 paragraph need statement grounding the request in trauma prevalence, the CAC model gap, and {{LOCAL: ...}} placeholders for local data.",
  evidenceBase:
    "The research case: 4–6 short paragraphs covering CAC effectiveness, trauma screening, family advocacy, MDT coordination, and trafficking response. This is the densest citation section.",
  interventionRationale:
    "Why THIS intervention (expanded screening + family advocacy + MDT coordination) is the evidence-supported response to the documented need. Connect mechanisms to outcomes.",
  logicModel:
    "An outcome logic model as markdown with headed lists: Inputs, Activities, Outputs, Short-Term Outcomes (1 yr), Intermediate Outcomes (2–3 yrs), Long-Term Outcomes. Cite evidence where an outcome link is research-supported.",
  funderLanguage:
    "8–12 ready-to-use phrases/sentences under headings 'For federal reviewers', 'For private/family foundations', and 'Universal' — each tuned to that audience's vocabulary (evidence-based, measurable outcomes vs. healing, community, every child).",
  proposalParagraphs:
    "3–4 polished, drop-in proposal paragraphs (need + approach + evidence) ready to paste into a standard foundation proposal.",
  conceptNote:
    "A complete one-page concept note: header line, problem, solution, evidence snapshot, the $350,000 request, outcomes, and a closing ask. Tight enough to fit one page.",
  federalVersion:
    "Federal proposal framing (OJJDP/OVC register): problem statement with citations, goals/objectives in SMART form, performance-measure-ready outcomes, references to evidence-based practice and MDT protocols.",
  foundationVersion:
    "Family foundation framing: warmer narrative voice, story-forward using composite/anonymized framing ONLY (never real case details), impact per dollar, donor-meaningful outcomes, light citations.",
};

function citationLine(c: Citation): string {
  return `[${c.id}] ${c.authors} (${c.year}). ${c.title}. ${c.source}. Finding: ${c.finding}`;
}

export function buildEvidenceContext(
  request: string,
  consensusCitations: Citation[]
): string {
  const anchorBlock = ANCHOR_LIBRARY.map(citationLine).join("\n");
  const consensusBlock = consensusCitations.map(citationLine).join("\n");

  return `You are a senior grants strategist for an NCA-accredited Children's Advocacy Center (Project Harmony, Omaha, Nebraska — serving eastern Nebraska and southwest Iowa, ~20 FTE, programs spanning forensic response, evidence-based treatment, family advocacy, prevention, a Training Institute, and Missing and Anti-Trafficking Youth Services).

FUNDING REQUEST:
"${request}"

EVIDENCE YOU MAY CITE — and the ONLY evidence you may cite:

== ANCHOR LIBRARY (cite as [A1]...[A11]) ==
${anchorBlock}

== CONSENSUS-RETRIEVED PEER-REVIEWED SOURCES (cite as [C1], [C2], ...) ==
${consensusBlock || "(none retrieved this run — rely on anchor library only)"}

CITATION INTEGRITY RULES (non-negotiable):
- Every empirical claim must carry an inline marker like [A2] or [C3].
- NEVER invent a citation, statistic, author, or year. If the evidence above does not support a claim, either omit it or write it as a program assertion without a citation marker.
- Do not cite anything not listed above.
- Local Omaha/Nebraska statistics: do NOT fabricate. Use placeholders like {{LOCAL: NE DHHS substantiated maltreatment count, most recent year}} so staff can insert verified local data.`;
}

export function buildSectionPrompt(
  evidenceContext: string,
  label: string,
  sectionKey: string
): string {
  return `${evidenceContext}

TASK: Write ONLY the "${label}" section of the evidence packet.
Section brief: ${SECTION_SPECS[sectionKey]}

Constraints:
- Respond with the raw markdown of this one section and NOTHING else — no JSON, no code fences, no preamble like "Here is...", no closing commentary, no top-level title (the UI supplies the section heading).
- Keep it under ~550 words so it completes within the response limit.
- Use the inline citation markers and {{LOCAL: ...}} placeholders per the rules above.`;
}
